
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.pruebagramaticareproductor.gramatica;

/** CUP generated class containing symbol constants. */
public class ServerParserSym {
  /* terminals */
  public static final int NUMERO = 65;
  public static final int PR_CONTINUAR = 20;
  public static final int IGUALACION = 42;
  public static final int PR_MENSAJE = 26;
  public static final int PR_ORDENAR = 23;
  public static final int ALFANUMERICO = 66;
  public static final int SUMA_EN_UNO = 61;
  public static final int PR_DOBLE = 5;
  public static final int XOR = 52;
  public static final int RESTA = 55;
  public static final int PR_LONGITUD = 25;
  public static final int PR_REPRODUCIR = 21;
  public static final int SUMA_SIMPLIFICADA = 60;
  public static final int NOT = 53;
  public static final int AND = 49;
  public static final int PR_PISTAS = 31;
  public static final int IGUAL = 41;
  public static final int PR_CADENA = 8;
  public static final int NOR = 51;
  public static final int NAND = 50;
  public static final int PR_HACER = 18;
  public static final int PR_SWITCH = 13;
  public static final int TABULACION = 38;
  public static final int PR_PARA = 16;
  public static final int SUMA = 54;
  public static final int PR_SUMARIZAR = 24;
  public static final int PUNTO_COMA = 37;
  public static final int PR_BOOLEAN = 6;
  public static final int EOF = 0;
  public static final int TRUE = 63;
  public static final int error = 1;
  public static final int NULO = 48;
  public static final int DENDENTACION = 40;
  public static final int COMA = 36;
  public static final int MODULO = 58;
  public static final int MAYOR_QUE = 44;
  public static final int PR_CASO = 14;
  public static final int PR_RETORNA = 19;
  public static final int DIFERENCIACION = 43;
  public static final int INDENTACION = 39;
  public static final int POTENCIA = 59;
  public static final int PR_DEFAULT = 15;
  public static final int PR_CARACTER = 7;
  public static final int RESTA_EN_UNO = 62;
  public static final int MAYOR_IGUAL = 46;
  public static final int PR_EXTIENDE = 3;
  public static final int PR_RANDOM = 29;
  public static final int PR_VAR = 9;
  public static final int PR_MIENTRAS = 17;
  public static final int PARC = 35;
  public static final int PR_ESPERAR = 22;
  public static final int PR_SINO = 12;
  public static final int PR_CIRCULAR = 30;
  public static final int PARA = 34;
  public static final int PR_PISTA = 2;
  public static final int MENOR_QUE = 45;
  public static final int CORC = 33;
  public static final int MENOR_IGUAL = 47;
  public static final int PR_ENTERO = 4;
  public static final int FALSE = 64;
  public static final int PR_SI = 11;
  public static final int PR_PRINCIPAL = 27;
  public static final int CORA = 32;
  public static final int SALTO = 67;
  public static final int DIVISION = 57;
  public static final int PR_KEEP = 10;
  public static final int PR_LISTA = 28;
  public static final int MULTIPLICACION = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_PISTA",
  "PR_EXTIENDE",
  "PR_ENTERO",
  "PR_DOBLE",
  "PR_BOOLEAN",
  "PR_CARACTER",
  "PR_CADENA",
  "PR_VAR",
  "PR_KEEP",
  "PR_SI",
  "PR_SINO",
  "PR_SWITCH",
  "PR_CASO",
  "PR_DEFAULT",
  "PR_PARA",
  "PR_MIENTRAS",
  "PR_HACER",
  "PR_RETORNA",
  "PR_CONTINUAR",
  "PR_REPRODUCIR",
  "PR_ESPERAR",
  "PR_ORDENAR",
  "PR_SUMARIZAR",
  "PR_LONGITUD",
  "PR_MENSAJE",
  "PR_PRINCIPAL",
  "PR_LISTA",
  "PR_RANDOM",
  "PR_CIRCULAR",
  "PR_PISTAS",
  "CORA",
  "CORC",
  "PARA",
  "PARC",
  "COMA",
  "PUNTO_COMA",
  "TABULACION",
  "INDENTACION",
  "DENDENTACION",
  "IGUAL",
  "IGUALACION",
  "DIFERENCIACION",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "NULO",
  "AND",
  "NAND",
  "NOR",
  "XOR",
  "NOT",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "POTENCIA",
  "SUMA_SIMPLIFICADA",
  "SUMA_EN_UNO",
  "RESTA_EN_UNO",
  "TRUE",
  "FALSE",
  "NUMERO",
  "ALFANUMERICO",
  "SALTO"
  };
}

