// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: ServerLexer.jflex

package com.froi.pruebagramaticareproductor.gramatica;

import java_cup.runtime.*;
import static com.froi.pruebagramaticareproductor.gramatica.ServerParserSym.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class ServerLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\4"+
    "\1\5\3\0\1\6\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\0\1\16\12\17\1\0\1\20"+
    "\1\21\1\22\1\23\2\0\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\24\1\32\2\24\1\33\1\34\1\35"+
    "\1\24\1\36\1\37\1\24\1\40\1\41\1\42\1\24"+
    "\1\43\4\24\1\44\1\0\1\45\1\46\2\0\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\33\1\61\1\62\1\63\1\64\1\65\1\24"+
    "\1\66\1\67\1\70\1\71\1\43\1\72\1\73\1\24"+
    "\1\74\1\0\1\75\u0183\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\20\23\1\24\1\25\1\26"+
    "\1\27\1\0\1\30\1\0\1\31\1\32\1\33\1\34"+
    "\1\35\1\0\1\36\1\37\1\40\1\0\26\23\1\41"+
    "\4\23\1\42\1\43\2\0\35\23\1\44\1\0\3\23"+
    "\1\45\11\23\1\46\5\23\1\47\5\23\1\50\2\23"+
    "\1\51\6\23\1\52\3\23\1\53\1\54\1\55\4\23"+
    "\1\56\7\23\1\57\4\23\1\60\6\23\1\61\1\23"+
    "\1\62\3\23\1\63\1\64\3\23\1\65\1\66\2\23"+
    "\1\67\1\23\1\70\2\23\1\71\1\23\1\72\1\73"+
    "\1\23\1\74\1\75\1\76\3\23\1\77\1\100\1\23"+
    "\1\101\1\102";

  private static int [] zzUnpackAction() {
    int [] result = new int[217];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\76\0\76\0\272\0\76\0\370"+
    "\0\76\0\76\0\76\0\u0136\0\76\0\u0174\0\76\0\u01b2"+
    "\0\76\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364"+
    "\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\u0554"+
    "\0\u0592\0\u05d0\0\u060e\0\u064c\0\76\0\76\0\76\0\76"+
    "\0\u068a\0\76\0\u06c8\0\76\0\76\0\76\0\76\0\76"+
    "\0\u0706\0\76\0\76\0\76\0\u0744\0\u0782\0\u07c0\0\u07fe"+
    "\0\u083c\0\u087a\0\u08b8\0\u08f6\0\u0934\0\u0972\0\u09b0\0\u09ee"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde"+
    "\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u0d14\0\u0d52\0\u0d90\0\u0dce"+
    "\0\76\0\76\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\u0f42"+
    "\0\u0f80\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132"+
    "\0\u1170\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322"+
    "\0\u1360\0\u139e\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512"+
    "\0\u1550\0\u02aa\0\u158e\0\u15cc\0\u160a\0\u1648\0\u02aa\0\u1686"+
    "\0\u16c4\0\u1702\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u1838\0\u1876"+
    "\0\u02aa\0\u18b4\0\u18f2\0\u1930\0\u196e\0\u19ac\0\u02aa\0\u19ea"+
    "\0\u1a28\0\u1a66\0\u1aa4\0\u1ae2\0\u02aa\0\u1b20\0\u1b5e\0\u02aa"+
    "\0\u1b9c\0\u1bda\0\u1c18\0\u1c56\0\u1c94\0\u1cd2\0\u02aa\0\u1d10"+
    "\0\u1d4e\0\u1d8c\0\u02aa\0\u02aa\0\u02aa\0\u1dca\0\u1e08\0\u1e46"+
    "\0\u1e84\0\u1ec2\0\u1f00\0\u1f3e\0\u1f7c\0\u1fba\0\u1ff8\0\u2036"+
    "\0\u2074\0\u02aa\0\u20b2\0\u20f0\0\u212e\0\u216c\0\u02aa\0\u21aa"+
    "\0\u21e8\0\u2226\0\u2264\0\u22a2\0\u22e0\0\u02aa\0\u231e\0\u02aa"+
    "\0\u235c\0\u239a\0\u23d8\0\u02aa\0\u02aa\0\u2416\0\u2454\0\u2492"+
    "\0\u02aa\0\u02aa\0\u24d0\0\u250e\0\u02aa\0\u254c\0\u02aa\0\u258a"+
    "\0\u25c8\0\u02aa\0\u2606\0\u02aa\0\u02aa\0\u2644\0\u02aa\0\u02aa"+
    "\0\u02aa\0\u2682\0\u26c0\0\u26fe\0\u02aa\0\u02aa\0\u273c\0\u02aa"+
    "\0\u02aa";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[217];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\25\1\33\2\25"+
    "\1\35\1\36\1\25\1\37\1\40\1\41\1\42\1\43"+
    "\4\25\1\2\77\0\1\3\101\0\1\50\1\0\1\51"+
    "\12\0\1\52\52\0\1\53\7\0\1\54\65\0\1\55"+
    "\13\0\1\56\6\0\1\57\70\0\1\60\77\0\1\20"+
    "\4\0\20\25\3\0\26\25\16\0\1\61\4\0\1\62"+
    "\75\0\1\63\75\0\1\64\1\65\71\0\1\25\4\0"+
    "\20\25\3\0\26\25\20\0\1\25\4\0\20\25\3\0"+
    "\15\25\1\66\10\25\20\0\1\25\4\0\20\25\3\0"+
    "\1\67\7\25\1\70\4\25\1\71\10\25\20\0\1\25"+
    "\4\0\20\25\3\0\4\25\1\72\10\25\1\73\10\25"+
    "\20\0\1\25\4\0\20\25\3\0\14\25\1\74\3\25"+
    "\1\75\3\25\1\76\1\25\20\0\1\25\4\0\20\25"+
    "\3\0\1\77\25\25\20\0\1\25\4\0\20\25\3\0"+
    "\1\100\25\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\101\21\25\20\0\1\25\4\0\20\25\3\0\10\25"+
    "\1\102\4\25\1\103\10\25\20\0\1\25\4\0\20\25"+
    "\3\0\4\25\1\104\3\25\1\105\15\25\20\0\1\25"+
    "\4\0\20\25\3\0\17\25\1\106\6\25\20\0\1\25"+
    "\4\0\20\25\3\0\1\107\7\25\1\110\6\25\1\111"+
    "\6\25\20\0\1\25\4\0\20\25\3\0\1\112\3\25"+
    "\1\113\21\25\20\0\1\25\4\0\20\25\3\0\10\25"+
    "\1\114\11\25\1\115\1\116\2\25\20\0\1\25\4\0"+
    "\20\25\3\0\17\25\1\117\6\25\20\0\1\25\4\0"+
    "\20\25\3\0\1\120\25\25\10\0\1\121\163\0\1\122"+
    "\15\123\1\124\60\123\2\65\1\5\1\0\72\65\17\0"+
    "\1\25\4\0\20\25\3\0\15\25\1\125\10\25\20\0"+
    "\1\25\4\0\20\25\3\0\3\25\1\126\13\25\1\127"+
    "\1\130\5\25\20\0\1\25\4\0\20\25\3\0\17\25"+
    "\1\131\6\25\20\0\1\25\4\0\20\25\3\0\14\25"+
    "\1\132\11\25\20\0\1\25\4\0\20\25\3\0\5\25"+
    "\1\133\20\25\20\0\1\25\4\0\20\25\3\0\1\25"+
    "\1\134\24\25\20\0\1\25\4\0\20\25\3\0\21\25"+
    "\1\135\4\25\20\0\1\25\4\0\20\25\3\0\16\25"+
    "\1\136\7\25\20\0\1\25\4\0\20\25\3\0\21\25"+
    "\1\137\4\25\20\0\1\25\4\0\20\25\3\0\12\25"+
    "\1\140\13\25\20\0\1\25\4\0\20\25\3\0\2\25"+
    "\1\141\23\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\142\21\25\20\0\1\25\4\0\20\25\3\0\20\25"+
    "\1\143\5\25\20\0\1\25\4\0\20\25\3\0\14\25"+
    "\1\144\11\25\20\0\1\25\4\0\20\25\3\0\14\25"+
    "\1\145\11\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\146\21\25\20\0\1\25\4\0\20\25\3\0\3\25"+
    "\1\147\22\25\20\0\1\25\4\0\20\25\3\0\17\25"+
    "\1\150\6\25\20\0\1\25\4\0\20\25\3\0\20\25"+
    "\1\151\5\25\20\0\1\25\4\0\20\25\3\0\10\25"+
    "\1\152\15\25\20\0\1\25\4\0\20\25\3\0\14\25"+
    "\1\153\11\25\20\0\1\25\4\0\20\25\3\0\16\25"+
    "\1\154\2\25\1\155\4\25\20\0\1\25\4\0\20\25"+
    "\3\0\14\25\1\156\11\25\20\0\1\25\4\0\20\25"+
    "\3\0\13\25\1\157\12\25\20\0\1\25\4\0\20\25"+
    "\3\0\10\25\1\160\15\25\20\0\1\25\4\0\20\25"+
    "\3\0\22\25\1\161\3\25\20\0\1\25\4\0\20\25"+
    "\3\0\17\25\1\162\6\25\1\0\15\123\1\163\60\123"+
    "\15\0\1\124\5\0\1\5\71\0\1\25\4\0\20\25"+
    "\3\0\12\25\1\164\13\25\20\0\1\25\4\0\20\25"+
    "\3\0\4\25\1\165\21\25\20\0\1\25\4\0\20\25"+
    "\3\0\1\166\25\25\20\0\1\25\4\0\20\25\3\0"+
    "\15\25\1\167\10\25\20\0\1\25\4\0\20\25\3\0"+
    "\2\25\1\170\23\25\20\0\1\25\4\0\20\25\3\0"+
    "\21\25\1\171\4\25\20\0\1\25\4\0\20\25\3\0"+
    "\1\172\25\25\20\0\1\25\4\0\20\25\3\0\12\25"+
    "\1\173\13\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\174\21\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\175\21\25\20\0\1\25\4\0\20\25\3\0\10\25"+
    "\1\176\15\25\20\0\1\25\4\0\20\25\3\0\20\25"+
    "\1\177\5\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\200\21\25\20\0\1\25\4\0\20\25\3\0\16\25"+
    "\1\201\7\25\20\0\1\25\4\0\20\25\3\0\21\25"+
    "\1\202\4\25\20\0\1\25\4\0\20\25\3\0\6\25"+
    "\1\203\17\25\20\0\1\25\4\0\20\25\3\0\20\25"+
    "\1\204\5\25\20\0\1\25\4\0\20\25\3\0\14\25"+
    "\1\205\11\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\206\21\25\20\0\1\25\4\0\20\25\3\0\1\207"+
    "\25\25\20\0\1\25\4\0\20\25\3\0\21\25\1\210"+
    "\4\25\20\0\1\25\4\0\20\25\3\0\14\25\1\211"+
    "\11\25\20\0\1\25\4\0\20\25\3\0\3\25\1\212"+
    "\22\25\20\0\1\25\4\0\20\25\3\0\17\25\1\213"+
    "\6\25\20\0\1\25\4\0\20\25\3\0\15\25\1\214"+
    "\10\25\20\0\1\25\4\0\20\25\3\0\15\25\1\215"+
    "\10\25\20\0\1\25\4\0\20\25\3\0\1\216\25\25"+
    "\20\0\1\25\4\0\20\25\3\0\21\25\1\217\4\25"+
    "\20\0\1\25\4\0\20\25\3\0\4\25\1\220\21\25"+
    "\1\0\15\123\1\163\5\123\1\5\52\123\17\0\1\25"+
    "\4\0\20\25\3\0\4\25\1\221\21\25\20\0\1\25"+
    "\4\0\20\25\3\0\14\25\1\222\11\25\20\0\1\25"+
    "\4\0\20\25\3\0\2\25\1\223\23\25\20\0\1\25"+
    "\4\0\20\25\3\0\22\25\1\224\3\25\20\0\1\25"+
    "\4\0\20\25\3\0\10\25\1\225\15\25\20\0\1\25"+
    "\4\0\20\25\3\0\22\25\1\226\3\25\20\0\1\25"+
    "\4\0\20\25\3\0\4\25\1\227\21\25\20\0\1\25"+
    "\4\0\20\25\3\0\17\25\1\230\6\25\20\0\1\25"+
    "\4\0\20\25\3\0\17\25\1\231\6\25\20\0\1\25"+
    "\4\0\20\25\3\0\4\25\1\232\21\25\20\0\1\25"+
    "\4\0\20\25\3\0\4\25\1\233\21\25\20\0\1\25"+
    "\4\0\20\25\3\0\17\25\1\234\6\25\20\0\1\25"+
    "\4\0\20\25\3\0\1\235\25\25\20\0\1\25\4\0"+
    "\20\25\3\0\10\25\1\236\15\25\20\0\1\25\4\0"+
    "\20\25\3\0\1\237\25\25\20\0\1\25\4\0\20\25"+
    "\3\0\21\25\1\240\4\25\20\0\1\25\4\0\20\25"+
    "\3\0\14\25\1\241\11\25\20\0\1\25\4\0\20\25"+
    "\3\0\1\242\25\25\20\0\1\25\4\0\20\25\3\0"+
    "\2\25\1\243\23\25\20\0\1\25\4\0\20\25\3\0"+
    "\15\25\1\244\10\25\20\0\1\25\4\0\20\25\3\0"+
    "\15\25\1\245\10\25\20\0\1\25\4\0\20\25\3\0"+
    "\17\25\1\246\6\25\20\0\1\25\4\0\20\25\3\0"+
    "\17\25\1\247\6\25\20\0\1\25\4\0\20\25\3\0"+
    "\2\25\1\250\23\25\20\0\1\25\4\0\20\25\3\0"+
    "\1\251\25\25\20\0\1\25\4\0\20\25\3\0\1\252"+
    "\25\25\20\0\1\25\4\0\20\25\3\0\21\25\1\253"+
    "\4\25\20\0\1\25\4\0\20\25\3\0\12\25\1\254"+
    "\13\25\20\0\1\25\4\0\20\25\3\0\14\25\1\255"+
    "\11\25\20\0\1\25\4\0\20\25\3\0\12\25\1\256"+
    "\13\25\20\0\1\25\4\0\20\25\3\0\15\25\1\257"+
    "\10\25\20\0\1\25\4\0\20\25\3\0\1\260\25\25"+
    "\20\0\1\25\4\0\20\25\3\0\14\25\1\261\11\25"+
    "\20\0\1\25\4\0\20\25\3\0\21\25\1\262\4\25"+
    "\20\0\1\25\4\0\20\25\3\0\11\25\1\263\14\25"+
    "\20\0\1\25\4\0\20\25\3\0\17\25\1\264\6\25"+
    "\20\0\1\25\4\0\20\25\3\0\1\265\25\25\20\0"+
    "\1\25\4\0\20\25\3\0\20\25\1\266\5\25\20\0"+
    "\1\25\4\0\20\25\3\0\10\25\1\267\15\25\20\0"+
    "\1\25\4\0\20\25\3\0\13\25\1\270\12\25\20\0"+
    "\1\25\4\0\20\25\3\0\3\25\1\271\22\25\20\0"+
    "\1\25\4\0\20\25\3\0\14\25\1\272\11\25\20\0"+
    "\1\25\4\0\20\25\3\0\10\25\1\273\15\25\20\0"+
    "\1\25\4\0\20\25\3\0\7\25\1\274\16\25\20\0"+
    "\1\25\4\0\20\25\3\0\14\25\1\275\11\25\20\0"+
    "\1\25\4\0\20\25\3\0\4\25\1\276\21\25\20\0"+
    "\1\25\4\0\20\25\3\0\1\277\25\25\20\0\1\25"+
    "\4\0\20\25\3\0\22\25\1\300\3\25\20\0\1\25"+
    "\4\0\20\25\3\0\21\25\1\301\4\25\20\0\1\25"+
    "\4\0\20\25\3\0\17\25\1\302\6\25\20\0\1\25"+
    "\4\0\20\25\3\0\3\25\1\303\22\25\20\0\1\25"+
    "\4\0\20\25\3\0\22\25\1\304\3\25\20\0\1\25"+
    "\4\0\20\25\3\0\4\25\1\305\21\25\20\0\1\25"+
    "\4\0\20\25\3\0\1\306\25\25\20\0\1\25\4\0"+
    "\20\25\3\0\17\25\1\307\6\25\20\0\1\25\4\0"+
    "\20\25\3\0\16\25\1\310\7\25\20\0\1\25\4\0"+
    "\20\25\3\0\22\25\1\311\3\25\20\0\1\25\4\0"+
    "\20\25\3\0\1\312\25\25\20\0\1\25\4\0\20\25"+
    "\3\0\25\25\1\313\20\0\1\25\4\0\20\25\3\0"+
    "\17\25\1\314\6\25\20\0\1\25\4\0\20\25\3\0"+
    "\17\25\1\315\6\25\20\0\1\25\4\0\20\25\3\0"+
    "\1\316\25\25\20\0\1\25\4\0\20\25\3\0\4\25"+
    "\1\317\21\25\20\0\1\25\4\0\20\25\3\0\3\25"+
    "\1\320\22\25\20\0\1\25\4\0\20\25\3\0\20\25"+
    "\1\321\5\25\20\0\1\25\4\0\20\25\3\0\1\322"+
    "\25\25\20\0\1\25\4\0\20\25\3\0\2\25\1\323"+
    "\23\25\20\0\1\25\4\0\20\25\3\0\1\324\25\25"+
    "\20\0\1\25\4\0\20\25\3\0\17\25\1\325\6\25"+
    "\20\0\1\25\4\0\20\25\3\0\12\25\1\326\13\25"+
    "\20\0\1\25\4\0\20\25\3\0\10\25\1\327\15\25"+
    "\20\0\1\25\4\0\20\25\3\0\17\25\1\330\6\25"+
    "\20\0\1\25\4\0\20\25\3\0\17\25\1\331\6\25"+
    "\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10106];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\1\1\1\11\1\1\3\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\23\1\4\11"+
    "\1\0\1\11\1\0\5\11\1\0\3\11\1\0\33\1"+
    "\2\11\2\0\36\1\1\0\146\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[217];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /*CODIGO AÑADIDO*/
    int nivelIndentacion = 0;

    public int verificarIndentacion(String tabulaciones) {
        
        String tab = tabulaciones + ".";
        String tabArray[] = tab.split("\t");
        System.out.println("\n\nnivel actual: " + nivelIndentacion + "\nIndentacion Nueva: " + (tabArray.length-1) + "\n\n");
        return tabArray.length - 1;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ServerLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    /*CODIGO EJECUTADO AL FINAL DEL ANALISIS*/
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(ServerParserSym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /*Se ejecuta al encontrar un error léxico*/
            }
            // fall through
          case 67: break;
          case 2:
            { int indentacionActual = verificarIndentacion(yytext());
                                    if(indentacionActual == nivelIndentacion) {
                                        /*Ignore*/
                                    } else if(indentacionActual > nivelIndentacion) {
                                        nivelIndentacion = indentacionActual;
                                        System.out.println("INDENTACION"); 
                                        return new Symbol(INDENTACION, yyline+1, yycolumn+1, yytext());
                                    } else if (indentacionActual < nivelIndentacion) {
                                        nivelIndentacion = indentacionActual;
                                        System.out.println("DENDENTACION"); 
                                        return new Symbol(DENDENTACION, yyline+1, yycolumn+1, yytext());
                                    }
            }
            // fall through
          case 68: break;
          case 3:
            { System.out.println("SALTO"); return new Symbol(SALTO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 69: break;
          case 4:
            { /*IGNORE*/
            }
            // fall through
          case 70: break;
          case 5:
            { System.out.println("NOT"); return new Symbol(NOT, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 71: break;
          case 6:
            { System.out.println("MODULO"); return new Symbol(MODULO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 72: break;
          case 7:
            { System.out.println("PARA"); return new Symbol(PARA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 73: break;
          case 8:
            { System.out.println("PARC"); return new Symbol(PARC, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 74: break;
          case 9:
            { System.out.println("MULTIPLICACION"); return new Symbol(MULTIPLICACION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 75: break;
          case 10:
            { System.out.println("SUMA"); return new Symbol(SUMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 76: break;
          case 11:
            { System.out.println("COMA"); return new Symbol(COMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 77: break;
          case 12:
            { System.out.println("RESTA"); return new Symbol(RESTA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 78: break;
          case 13:
            { System.out.println("DIVISION"); return new Symbol(DIVISION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 79: break;
          case 14:
            { System.out.println("NUMERO"); return new Symbol(NUMERO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 80: break;
          case 15:
            { System.out.println("PUNTO_COMA"); return new Symbol(PUNTO_COMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 81: break;
          case 16:
            { System.out.println("MENOR_QUE"); return new Symbol(MENOR_QUE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 82: break;
          case 17:
            { System.out.println("IGUAL"); return new Symbol(IGUAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 83: break;
          case 18:
            { System.out.println("MAYOR_QUE"); return new Symbol(MAYOR_QUE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 84: break;
          case 19:
            { System.out.println("ALFANUMERICO"); return new Symbol(ALFANUMERICO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 85: break;
          case 20:
            { System.out.println("CORA"); return new Symbol(CORA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 86: break;
          case 21:
            { System.out.println("CORC"); return new Symbol(CORC, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 87: break;
          case 22:
            { System.out.println("POTENCIA"); return new Symbol(POTENCIA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 88: break;
          case 23:
            { System.out.println("NULO"); return new Symbol(NULO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 89: break;
          case 24:
            { System.out.println("DIFERENCIACION"); return new Symbol(DIFERENCIACION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 90: break;
          case 25:
            { System.out.println("AND"); return new Symbol(AND, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 91: break;
          case 26:
            { System.out.println("XOR"); return new Symbol(XOR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 92: break;
          case 27:
            { System.out.println("SUMA_EN_UNO"); return new Symbol(SUMA_EN_UNO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 93: break;
          case 28:
            { System.out.println("SUMA_SIMPLIFICADA"); return new Symbol(SUMA_SIMPLIFICADA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 94: break;
          case 29:
            { System.out.println("RESTA_EN_UNO"); return new Symbol(RESTA_EN_UNO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 95: break;
          case 30:
            { System.out.println("MENOR_IGUAL"); return new Symbol(MENOR_IGUAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 96: break;
          case 31:
            { System.out.println("IGUALACION"); return new Symbol(IGUALACION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 97: break;
          case 32:
            { System.out.println("MAYOR_IGUAL"); return new Symbol(MAYOR_IGUAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 98: break;
          case 33:
            { System.out.println("SI"); return new Symbol(PR_SI, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 99: break;
          case 34:
            { System.out.println("NAND"); return new Symbol(NAND, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 100: break;
          case 35:
            { System.out.println("NOR"); return new Symbol(NOR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 101: break;
          case 36:
            { System.out.println("VAR"); return new Symbol(PR_VAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 102: break;
          case 37:
            { System.out.println("CASO"); return new Symbol(PR_CASO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 103: break;
          case 38:
            { System.out.println("KEEP"); return new Symbol(PR_KEEP, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 104: break;
          case 39:
            { System.out.println("PARA"); return new Symbol(PR_PARA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 105: break;
          case 40:
            { System.out.println("SINO"); return new Symbol(PR_SINO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 106: break;
          case 41:
            { System.out.println("TRUE"); return new Symbol(TRUE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 107: break;
          case 42:
            { System.out.println("DOBLE"); return new Symbol(PR_DOBLE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 108: break;
          case 43:
            { System.out.println("FALSE"); return new Symbol(FALSE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 109: break;
          case 44:
            { System.out.println("HACER"); return new Symbol(PR_HACER, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 110: break;
          case 45:
            { System.out.println("LISTA"); return new Symbol(PR_LISTA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 111: break;
          case 46:
            { System.out.println("PISTA"); return new Symbol(PR_PISTA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 112: break;
          case 47:
            { System.out.println("CADENA"); return new Symbol(PR_CADENA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 113: break;
          case 48:
            { System.out.println("ENTERO"); return new Symbol(PR_ENTERO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 114: break;
          case 49:
            { System.out.println("PISTAS"); return new Symbol(PR_PISTAS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 115: break;
          case 50:
            { System.out.println("RANDOM"); return new Symbol(PR_RANDOM, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 116: break;
          case 51:
            { System.out.println("SWITCH"); return new Symbol(PR_SWITCH, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 117: break;
          case 52:
            { System.out.println("BOOLEAN"); return new Symbol(PR_BOOLEAN, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 118: break;
          case 53:
            { System.out.println("DEFAULT"); return new Symbol(PR_DEFAULT, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 119: break;
          case 54:
            { System.out.println("ESPERAR"); return new Symbol(PR_ESPERAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 120: break;
          case 55:
            { System.out.println("MENSAJE"); return new Symbol(PR_MENSAJE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 121: break;
          case 56:
            { System.out.println("ORDENAR"); return new Symbol(PR_ORDENAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 122: break;
          case 57:
            { System.out.println("RETORNA"); return new Symbol(PR_RETORNA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 123: break;
          case 58:
            { System.out.println("CARACTER"); return new Symbol(PR_CARACTER, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 124: break;
          case 59:
            { System.out.println("CIRCULAR"); return new Symbol(PR_CIRCULAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 125: break;
          case 60:
            { System.out.println("EXTIENDE"); return new Symbol(PR_EXTIENDE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 126: break;
          case 61:
            { System.out.println("LONGITUD"); return new Symbol(PR_LONGITUD, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 127: break;
          case 62:
            { System.out.println("MIENTRAS"); return new Symbol(PR_MIENTRAS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 128: break;
          case 63:
            { System.out.println("CONTINUAR"); return new Symbol(PR_CONTINUAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 129: break;
          case 64:
            { System.out.println("PRINCIPAL"); return new Symbol(PR_PRINCIPAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 130: break;
          case 65:
            { System.out.println("SUMARIZAR"); return new Symbol(PR_SUMARIZAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 131: break;
          case 66:
            { System.out.println("REPRODUCIR"); return new Symbol(PR_REPRODUCIR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 132: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}