// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: ServerLexer.jflex

package com.froi.pruebagramaticareproductor.gramatica;

import java_cup.runtime.*;
import static com.froi.pruebagramaticareproductor.gramatica.ServerParserSym.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class ServerLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\4"+
    "\1\5\3\0\1\6\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\0\1\16\12\17\1\0\1\20"+
    "\1\21\1\22\1\23\2\0\1\17\1\24\1\25\1\26"+
    "\1\27\1\30\1\17\1\31\2\17\1\32\1\33\1\34"+
    "\1\17\1\35\1\36\1\17\1\37\1\40\1\41\1\17"+
    "\1\42\4\17\1\43\1\0\1\44\1\45\2\0\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\32\1\60\1\61\1\62\1\63\1\64\1\17"+
    "\1\65\1\66\1\67\1\70\1\42\1\71\2\17\1\72"+
    "\1\0\1\73\u0183\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\1\1\21\17\16\1\22\1\23\1\24"+
    "\1\25\1\0\1\26\1\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\0\1\34\1\35\1\36\1\0\25\16\1\37"+
    "\4\16\1\40\1\41\2\0\34\16\1\42\1\0\3\16"+
    "\1\43\10\16\1\44\5\16\1\45\5\16\1\46\2\16"+
    "\1\47\6\16\1\50\2\16\1\51\1\52\1\53\4\16"+
    "\1\54\7\16\1\55\4\16\1\56\5\16\1\57\1\16"+
    "\1\60\3\16\1\61\1\62\3\16\1\63\1\64\1\16"+
    "\1\65\1\16\1\66\2\16\1\67\1\16\1\70\1\71"+
    "\1\16\1\72\1\73\3\16\1\74\1\75\1\16\1\76"+
    "\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[209];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\74\0\74\0\264\0\74\0\360"+
    "\0\74\0\74\0\74\0\u012c\0\74\0\u0168\0\74\0\u01a4"+
    "\0\74\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348"+
    "\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528"+
    "\0\u0564\0\u05a0\0\u05dc\0\74\0\74\0\74\0\74\0\u0618"+
    "\0\74\0\u0654\0\74\0\74\0\74\0\74\0\74\0\u0690"+
    "\0\74\0\74\0\74\0\u06cc\0\u0708\0\u0744\0\u0780\0\u07bc"+
    "\0\u07f8\0\u0834\0\u0870\0\u08ac\0\u08e8\0\u0924\0\u0960\0\u099c"+
    "\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40\0\u0b7c"+
    "\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4\0\74\0\74"+
    "\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4"+
    "\0\u0f00\0\u0f3c\0\u0f78\0\u0fb4\0\u0ff0\0\u102c\0\u1068\0\u10a4"+
    "\0\u10e0\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284"+
    "\0\u12c0\0\u12fc\0\u1338\0\u1374\0\u13b0\0\u13ec\0\u01a4\0\u1428"+
    "\0\u1464\0\u14a0\0\u14dc\0\u01a4\0\u1518\0\u1554\0\u1590\0\u15cc"+
    "\0\u1608\0\u1644\0\u1680\0\u16bc\0\u01a4\0\u16f8\0\u1734\0\u1770"+
    "\0\u17ac\0\u17e8\0\u01a4\0\u1824\0\u1860\0\u189c\0\u18d8\0\u1914"+
    "\0\u01a4\0\u1950\0\u198c\0\u01a4\0\u19c8\0\u1a04\0\u1a40\0\u1a7c"+
    "\0\u1ab8\0\u1af4\0\u01a4\0\u1b30\0\u1b6c\0\u01a4\0\u01a4\0\u01a4"+
    "\0\u1ba8\0\u1be4\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4\0\u1d10\0\u1d4c"+
    "\0\u1d88\0\u1dc4\0\u1e00\0\u1e3c\0\u01a4\0\u1e78\0\u1eb4\0\u1ef0"+
    "\0\u1f2c\0\u01a4\0\u1f68\0\u1fa4\0\u1fe0\0\u201c\0\u2058\0\u01a4"+
    "\0\u2094\0\u01a4\0\u20d0\0\u210c\0\u2148\0\u01a4\0\u01a4\0\u2184"+
    "\0\u21c0\0\u21fc\0\u01a4\0\u01a4\0\u2238\0\u01a4\0\u2274\0\u01a4"+
    "\0\u22b0\0\u22ec\0\u01a4\0\u2328\0\u01a4\0\u01a4\0\u2364\0\u01a4"+
    "\0\u01a4\0\u23a0\0\u23dc\0\u2418\0\u01a4\0\u01a4\0\u2454\0\u01a4"+
    "\0\u01a4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[209];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\20\1\25"+
    "\1\26\1\27\1\30\1\31\1\20\1\32\2\20\1\34"+
    "\1\35\1\20\1\36\1\37\1\40\1\41\1\42\3\20"+
    "\1\2\75\0\1\3\77\0\1\47\1\0\1\50\12\0"+
    "\1\51\50\0\1\52\7\0\1\53\63\0\1\54\13\0"+
    "\1\55\6\0\1\56\66\0\1\57\75\0\1\20\4\0"+
    "\17\20\3\0\25\20\16\0\1\60\4\0\1\61\73\0"+
    "\1\62\73\0\1\63\1\64\67\0\1\20\4\0\17\20"+
    "\3\0\15\20\1\65\7\20\20\0\1\20\4\0\17\20"+
    "\3\0\1\66\7\20\1\67\4\20\1\70\7\20\20\0"+
    "\1\20\4\0\17\20\3\0\4\20\1\71\10\20\1\72"+
    "\7\20\20\0\1\20\4\0\17\20\3\0\14\20\1\73"+
    "\3\20\1\74\4\20\20\0\1\20\4\0\17\20\3\0"+
    "\1\75\24\20\20\0\1\20\4\0\17\20\3\0\1\76"+
    "\24\20\20\0\1\20\4\0\17\20\3\0\4\20\1\77"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\10\20\1\100"+
    "\4\20\1\101\7\20\20\0\1\20\4\0\17\20\3\0"+
    "\4\20\1\102\3\20\1\103\14\20\20\0\1\20\4\0"+
    "\17\20\3\0\17\20\1\104\5\20\20\0\1\20\4\0"+
    "\17\20\3\0\1\105\7\20\1\106\6\20\1\107\5\20"+
    "\20\0\1\20\4\0\17\20\3\0\1\110\3\20\1\111"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\10\20\1\112"+
    "\11\20\1\113\1\114\1\20\20\0\1\20\4\0\17\20"+
    "\3\0\17\20\1\115\5\20\20\0\1\20\4\0\17\20"+
    "\3\0\1\116\24\20\10\0\1\117\157\0\1\120\15\121"+
    "\1\122\56\121\2\64\1\5\1\0\70\64\17\0\1\20"+
    "\4\0\17\20\3\0\15\20\1\123\7\20\20\0\1\20"+
    "\4\0\17\20\3\0\3\20\1\124\13\20\1\125\1\126"+
    "\4\20\20\0\1\20\4\0\17\20\3\0\17\20\1\127"+
    "\5\20\20\0\1\20\4\0\17\20\3\0\14\20\1\130"+
    "\10\20\20\0\1\20\4\0\17\20\3\0\5\20\1\131"+
    "\17\20\20\0\1\20\4\0\17\20\3\0\1\20\1\132"+
    "\23\20\20\0\1\20\4\0\17\20\3\0\21\20\1\133"+
    "\3\20\20\0\1\20\4\0\17\20\3\0\16\20\1\134"+
    "\6\20\20\0\1\20\4\0\17\20\3\0\12\20\1\135"+
    "\12\20\20\0\1\20\4\0\17\20\3\0\2\20\1\136"+
    "\22\20\20\0\1\20\4\0\17\20\3\0\4\20\1\137"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\20\20\1\140"+
    "\4\20\20\0\1\20\4\0\17\20\3\0\14\20\1\141"+
    "\10\20\20\0\1\20\4\0\17\20\3\0\14\20\1\142"+
    "\10\20\20\0\1\20\4\0\17\20\3\0\4\20\1\143"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\3\20\1\144"+
    "\21\20\20\0\1\20\4\0\17\20\3\0\17\20\1\145"+
    "\5\20\20\0\1\20\4\0\17\20\3\0\20\20\1\146"+
    "\4\20\20\0\1\20\4\0\17\20\3\0\10\20\1\147"+
    "\14\20\20\0\1\20\4\0\17\20\3\0\14\20\1\150"+
    "\10\20\20\0\1\20\4\0\17\20\3\0\16\20\1\151"+
    "\2\20\1\152\3\20\20\0\1\20\4\0\17\20\3\0"+
    "\14\20\1\153\10\20\20\0\1\20\4\0\17\20\3\0"+
    "\13\20\1\154\11\20\20\0\1\20\4\0\17\20\3\0"+
    "\10\20\1\155\14\20\20\0\1\20\4\0\17\20\3\0"+
    "\22\20\1\156\2\20\20\0\1\20\4\0\17\20\3\0"+
    "\17\20\1\157\5\20\1\0\15\121\1\160\56\121\15\0"+
    "\1\122\5\0\1\5\67\0\1\20\4\0\17\20\3\0"+
    "\12\20\1\161\12\20\20\0\1\20\4\0\17\20\3\0"+
    "\4\20\1\162\20\20\20\0\1\20\4\0\17\20\3\0"+
    "\1\163\24\20\20\0\1\20\4\0\17\20\3\0\15\20"+
    "\1\164\7\20\20\0\1\20\4\0\17\20\3\0\2\20"+
    "\1\165\22\20\20\0\1\20\4\0\17\20\3\0\21\20"+
    "\1\166\3\20\20\0\1\20\4\0\17\20\3\0\1\167"+
    "\24\20\20\0\1\20\4\0\17\20\3\0\12\20\1\170"+
    "\12\20\20\0\1\20\4\0\17\20\3\0\4\20\1\171"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\4\20\1\172"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\20\20\1\173"+
    "\4\20\20\0\1\20\4\0\17\20\3\0\4\20\1\174"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\16\20\1\175"+
    "\6\20\20\0\1\20\4\0\17\20\3\0\21\20\1\176"+
    "\3\20\20\0\1\20\4\0\17\20\3\0\6\20\1\177"+
    "\16\20\20\0\1\20\4\0\17\20\3\0\20\20\1\200"+
    "\4\20\20\0\1\20\4\0\17\20\3\0\14\20\1\201"+
    "\10\20\20\0\1\20\4\0\17\20\3\0\4\20\1\202"+
    "\20\20\20\0\1\20\4\0\17\20\3\0\1\203\24\20"+
    "\20\0\1\20\4\0\17\20\3\0\21\20\1\204\3\20"+
    "\20\0\1\20\4\0\17\20\3\0\14\20\1\205\10\20"+
    "\20\0\1\20\4\0\17\20\3\0\3\20\1\206\21\20"+
    "\20\0\1\20\4\0\17\20\3\0\17\20\1\207\5\20"+
    "\20\0\1\20\4\0\17\20\3\0\15\20\1\210\7\20"+
    "\20\0\1\20\4\0\17\20\3\0\15\20\1\211\7\20"+
    "\20\0\1\20\4\0\17\20\3\0\1\212\24\20\20\0"+
    "\1\20\4\0\17\20\3\0\21\20\1\213\3\20\20\0"+
    "\1\20\4\0\17\20\3\0\4\20\1\214\20\20\1\0"+
    "\15\121\1\160\5\121\1\5\50\121\17\0\1\20\4\0"+
    "\17\20\3\0\4\20\1\215\20\20\20\0\1\20\4\0"+
    "\17\20\3\0\14\20\1\216\10\20\20\0\1\20\4\0"+
    "\17\20\3\0\2\20\1\217\22\20\20\0\1\20\4\0"+
    "\17\20\3\0\22\20\1\220\2\20\20\0\1\20\4\0"+
    "\17\20\3\0\10\20\1\221\14\20\20\0\1\20\4\0"+
    "\17\20\3\0\22\20\1\222\2\20\20\0\1\20\4\0"+
    "\17\20\3\0\4\20\1\223\20\20\20\0\1\20\4\0"+
    "\17\20\3\0\17\20\1\224\5\20\20\0\1\20\4\0"+
    "\17\20\3\0\17\20\1\225\5\20\20\0\1\20\4\0"+
    "\17\20\3\0\4\20\1\226\20\20\20\0\1\20\4\0"+
    "\17\20\3\0\17\20\1\227\5\20\20\0\1\20\4\0"+
    "\17\20\3\0\1\230\24\20\20\0\1\20\4\0\17\20"+
    "\3\0\10\20\1\231\14\20\20\0\1\20\4\0\17\20"+
    "\3\0\1\232\24\20\20\0\1\20\4\0\17\20\3\0"+
    "\21\20\1\233\3\20\20\0\1\20\4\0\17\20\3\0"+
    "\14\20\1\234\10\20\20\0\1\20\4\0\17\20\3\0"+
    "\1\235\24\20\20\0\1\20\4\0\17\20\3\0\2\20"+
    "\1\236\22\20\20\0\1\20\4\0\17\20\3\0\15\20"+
    "\1\237\7\20\20\0\1\20\4\0\17\20\3\0\15\20"+
    "\1\240\7\20\20\0\1\20\4\0\17\20\3\0\17\20"+
    "\1\241\5\20\20\0\1\20\4\0\17\20\3\0\17\20"+
    "\1\242\5\20\20\0\1\20\4\0\17\20\3\0\2\20"+
    "\1\243\22\20\20\0\1\20\4\0\17\20\3\0\1\244"+
    "\24\20\20\0\1\20\4\0\17\20\3\0\1\245\24\20"+
    "\20\0\1\20\4\0\17\20\3\0\21\20\1\246\3\20"+
    "\20\0\1\20\4\0\17\20\3\0\12\20\1\247\12\20"+
    "\20\0\1\20\4\0\17\20\3\0\14\20\1\250\10\20"+
    "\20\0\1\20\4\0\17\20\3\0\12\20\1\251\12\20"+
    "\20\0\1\20\4\0\17\20\3\0\15\20\1\252\7\20"+
    "\20\0\1\20\4\0\17\20\3\0\1\253\24\20\20\0"+
    "\1\20\4\0\17\20\3\0\21\20\1\254\3\20\20\0"+
    "\1\20\4\0\17\20\3\0\11\20\1\255\13\20\20\0"+
    "\1\20\4\0\17\20\3\0\17\20\1\256\5\20\20\0"+
    "\1\20\4\0\17\20\3\0\1\257\24\20\20\0\1\20"+
    "\4\0\17\20\3\0\20\20\1\260\4\20\20\0\1\20"+
    "\4\0\17\20\3\0\10\20\1\261\14\20\20\0\1\20"+
    "\4\0\17\20\3\0\13\20\1\262\11\20\20\0\1\20"+
    "\4\0\17\20\3\0\3\20\1\263\21\20\20\0\1\20"+
    "\4\0\17\20\3\0\14\20\1\264\10\20\20\0\1\20"+
    "\4\0\17\20\3\0\10\20\1\265\14\20\20\0\1\20"+
    "\4\0\17\20\3\0\7\20\1\266\15\20\20\0\1\20"+
    "\4\0\17\20\3\0\14\20\1\267\10\20\20\0\1\20"+
    "\4\0\17\20\3\0\4\20\1\270\20\20\20\0\1\20"+
    "\4\0\17\20\3\0\1\271\24\20\20\0\1\20\4\0"+
    "\17\20\3\0\22\20\1\272\2\20\20\0\1\20\4\0"+
    "\17\20\3\0\21\20\1\273\3\20\20\0\1\20\4\0"+
    "\17\20\3\0\17\20\1\274\5\20\20\0\1\20\4\0"+
    "\17\20\3\0\22\20\1\275\2\20\20\0\1\20\4\0"+
    "\17\20\3\0\4\20\1\276\20\20\20\0\1\20\4\0"+
    "\17\20\3\0\1\277\24\20\20\0\1\20\4\0\17\20"+
    "\3\0\17\20\1\300\5\20\20\0\1\20\4\0\17\20"+
    "\3\0\16\20\1\301\6\20\20\0\1\20\4\0\17\20"+
    "\3\0\22\20\1\302\2\20\20\0\1\20\4\0\17\20"+
    "\3\0\1\303\24\20\20\0\1\20\4\0\17\20\3\0"+
    "\24\20\1\304\20\0\1\20\4\0\17\20\3\0\17\20"+
    "\1\305\5\20\20\0\1\20\4\0\17\20\3\0\17\20"+
    "\1\306\5\20\20\0\1\20\4\0\17\20\3\0\1\307"+
    "\24\20\20\0\1\20\4\0\17\20\3\0\3\20\1\310"+
    "\21\20\20\0\1\20\4\0\17\20\3\0\20\20\1\311"+
    "\4\20\20\0\1\20\4\0\17\20\3\0\1\312\24\20"+
    "\20\0\1\20\4\0\17\20\3\0\2\20\1\313\22\20"+
    "\20\0\1\20\4\0\17\20\3\0\1\314\24\20\20\0"+
    "\1\20\4\0\17\20\3\0\17\20\1\315\5\20\20\0"+
    "\1\20\4\0\17\20\3\0\12\20\1\316\12\20\20\0"+
    "\1\20\4\0\17\20\3\0\10\20\1\317\14\20\20\0"+
    "\1\20\4\0\17\20\3\0\17\20\1\320\5\20\20\0"+
    "\1\20\4\0\17\20\3\0\17\20\1\321\5\20\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9360];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\1\1\1\11\1\1\3\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\22\1\4\11"+
    "\1\0\1\11\1\0\5\11\1\0\3\11\1\0\32\1"+
    "\2\11\2\0\35\1\1\0\141\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[209];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /*CODIGO AÑADIDO*/
    int nivelIndentacion = 0;

    public int verificarIndentacion(String tabulaciones) {
        
        String tab = tabulaciones + ".";
        String tabArray[] = tab.split("\t");
        System.out.println("\n\nnivel actual: " + nivelIndentacion + "\nIndentacion Nueva: " + (tabArray.length-1) + "\n\n");
        return tabArray.length - 1;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ServerLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    /*CODIGO EJECUTADO AL FINAL DEL ANALISIS*/
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(ServerParserSym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /*Se ejecuta al encontrar un error léxico*/
            }
            // fall through
          case 64: break;
          case 2:
            { int indentacionActual = verificarIndentacion(yytext());
                                    if(indentacionActual == nivelIndentacion) {
                                        /*Ignore*/
                                    } else if(indentacionActual > nivelIndentacion) {
                                        nivelIndentacion = indentacionActual;
                                        System.out.println("INDENTACION"); 
                                        return new Symbol(INDENTACION, yyline+1, yycolumn+1, yytext());
                                    } else if (indentacionActual < nivelIndentacion) {
                                        nivelIndentacion = indentacionActual;
                                        System.out.println("DENDENTACION"); 
                                        return new Symbol(DENDENTACION, yyline+1, yycolumn+1, yytext());
                                    }
            }
            // fall through
          case 65: break;
          case 3:
            { System.out.println("SALTO"); return new Symbol(SALTO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 66: break;
          case 4:
            { /*IGNORE*/
            }
            // fall through
          case 67: break;
          case 5:
            { System.out.println("NOT"); return new Symbol(NOT, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 68: break;
          case 6:
            { System.out.println("MODULO"); return new Symbol(MODULO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 69: break;
          case 7:
            { System.out.println("PARA"); return new Symbol(PARA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 70: break;
          case 8:
            { System.out.println("PARC"); return new Symbol(PARC, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 71: break;
          case 9:
            { System.out.println("MULTIPLICACION"); return new Symbol(MULTIPLICACION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 72: break;
          case 10:
            { System.out.println("SUMA"); return new Symbol(SUMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 73: break;
          case 11:
            { System.out.println("COMA"); return new Symbol(COMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 74: break;
          case 12:
            { System.out.println("RESTA"); return new Symbol(RESTA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 75: break;
          case 13:
            { System.out.println("DIVISION"); return new Symbol(DIVISION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 76: break;
          case 14:
            { System.out.println("ALFANUMERICO"); return new Symbol(ALFANUMERICO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 77: break;
          case 15:
            { System.out.println("PUNTO_COMA"); return new Symbol(PUNTO_COMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 78: break;
          case 16:
            { System.out.println("MENOR_QUE"); return new Symbol(MENOR_QUE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 79: break;
          case 17:
            { System.out.println("MAYOR_QUE"); return new Symbol(MAYOR_QUE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 80: break;
          case 18:
            { System.out.println("CORA"); return new Symbol(CORA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 81: break;
          case 19:
            { System.out.println("CORC"); return new Symbol(CORC, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 82: break;
          case 20:
            { System.out.println("POTENCIA"); return new Symbol(POTENCIA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 83: break;
          case 21:
            { System.out.println("NULO"); return new Symbol(NULO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 84: break;
          case 22:
            { System.out.println("DIFERENCIACION"); return new Symbol(DIFERENCIACION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 85: break;
          case 23:
            { System.out.println("AND"); return new Symbol(AND, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 86: break;
          case 24:
            { System.out.println("XOR"); return new Symbol(XOR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 87: break;
          case 25:
            { System.out.println("SUMA_EN_UNO"); return new Symbol(SUMA_EN_UNO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 88: break;
          case 26:
            { System.out.println("SUMA_SIMPLIFICADA"); return new Symbol(SUMA_SIMPLIFICADA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 89: break;
          case 27:
            { System.out.println("RESTA_EN_UNO"); return new Symbol(RESTA_EN_UNO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 90: break;
          case 28:
            { System.out.println("MENOR_IGUAL"); return new Symbol(MENOR_IGUAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 91: break;
          case 29:
            { System.out.println("IGUALACION"); return new Symbol(IGUALACION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 92: break;
          case 30:
            { System.out.println("MAYOR_IGUAL"); return new Symbol(MAYOR_IGUAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 93: break;
          case 31:
            { System.out.println("SI"); return new Symbol(PR_SI, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 94: break;
          case 32:
            { System.out.println("NAND"); return new Symbol(NAND, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 95: break;
          case 33:
            { System.out.println("NOR"); return new Symbol(NOR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 96: break;
          case 34:
            { System.out.println("VAR"); return new Symbol(PR_VAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 97: break;
          case 35:
            { System.out.println("CASO"); return new Symbol(PR_CASO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 98: break;
          case 36:
            { System.out.println("KEEP"); return new Symbol(PR_KEEP, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 99: break;
          case 37:
            { System.out.println("PARA"); return new Symbol(PR_PARA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 100: break;
          case 38:
            { System.out.println("SINO"); return new Symbol(PR_SINO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 101: break;
          case 39:
            { System.out.println("TRUE"); return new Symbol(TRUE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 102: break;
          case 40:
            { System.out.println("DOBLE"); return new Symbol(PR_DOBLE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 103: break;
          case 41:
            { System.out.println("FALSE"); return new Symbol(FALSE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 104: break;
          case 42:
            { System.out.println("HACER"); return new Symbol(PR_HACER, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 105: break;
          case 43:
            { System.out.println("LISTA"); return new Symbol(PR_LISTA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 106: break;
          case 44:
            { System.out.println("PISTA"); return new Symbol(PR_PISTA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 107: break;
          case 45:
            { System.out.println("CADENA"); return new Symbol(PR_CADENA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 108: break;
          case 46:
            { System.out.println("ENTERO"); return new Symbol(PR_ENTERO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 109: break;
          case 47:
            { System.out.println("PISTAS"); return new Symbol(PR_PISTAS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 110: break;
          case 48:
            { System.out.println("RANDOM"); return new Symbol(PR_RANDOM, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 111: break;
          case 49:
            { System.out.println("SWITCH"); return new Symbol(PR_SWITCH, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 112: break;
          case 50:
            { System.out.println("BOOLEAN"); return new Symbol(PR_BOOLEAN, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 113: break;
          case 51:
            { System.out.println("DEFAULT"); return new Symbol(PR_DEFAULT, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 114: break;
          case 52:
            { System.out.println("ESPERAR"); return new Symbol(PR_ESPERAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 115: break;
          case 53:
            { System.out.println("MENSAJE"); return new Symbol(PR_MENSAJE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 116: break;
          case 54:
            { System.out.println("ORDENAR"); return new Symbol(PR_ORDENAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 117: break;
          case 55:
            { System.out.println("RETORNA"); return new Symbol(PR_RETORNA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 118: break;
          case 56:
            { System.out.println("CARACTER"); return new Symbol(PR_CARACTER, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 119: break;
          case 57:
            { System.out.println("CIRCULAR"); return new Symbol(PR_CIRCULAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 120: break;
          case 58:
            { System.out.println("LONGITUD"); return new Symbol(PR_LONGITUD, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 121: break;
          case 59:
            { System.out.println("MIENTRAS"); return new Symbol(PR_MIENTRAS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 122: break;
          case 60:
            { System.out.println("CONTINUAR"); return new Symbol(PR_CONTINUAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 123: break;
          case 61:
            { System.out.println("PRINCIPAL"); return new Symbol(PR_PRINCIPAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 124: break;
          case 62:
            { System.out.println("SUMARIZAR"); return new Symbol(PR_SUMARIZAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 125: break;
          case 63:
            { System.out.println("REPRODUCIR"); return new Symbol(PR_REPRODUCIR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}